- name: Variable from the output section
  hosts: localhost
  connection : local
  become: true
  tasks:
    - name: run the uptime command
      ansible.builtin.shell:
        name: uptime
        register: out
    - name: print a ot
      ansible.builtin.debug:
        msg : "{{out}}"